### ISSUE TITLE
"Lost connection to PC" when Game Count ~47

### ISSUE THREAD

**Issue by n1ckn4m3** [moonlight-stream/moonlight-android#136]
I'm using a GPD XD with the latest SVN moonlight client, running GFE 2.8.1.21.  When my list of games in GFE is greater than 47, attempting to connect via the Android client brings a 'Lost connection to PC' error message and the nVidia Streamer Service and nVidia Streamer Network Service stop without generating any errors in the event log.  

If I remove a game from the library, stop NvBackend.exe, delete the GFE game cache files (%LocalAppData%\NVIDIA\NvBackend\journalBS.jour.dat and %LocalAppData%\NVIDIA\NvBackend\journalBS.main.xml), then restart the nVidia Streamer Service and GeForce Experience, I can again connect. 

It doesn't seem to matter what game the 48th game is, I've removed multiples and tried multiples to see if any combination of games let me have more than 47 successfully, but in every case it crashes the nVidia Streamer Service and fails to connect.

EDIT:  I've noticed that I can sometimes manually add games to SHIELD streaming without adding them to the GFE games list and it doesn't seem to cause the client to disconnect or the streamer services to crash unless I add box art, and not all box art makes it crash.  Some larger pixel size (e.g., 3000x2000, way bigger than necessary anyways) would cause it to crash.

I wonder if GFE is just piping boxart that is too much for the GPD XD's 2GB of RAM?

Of other note, this is the rooted .APK.  I had the same issue with the non-rooted .APK as well.

**Comment by DStBone** [comment]
I'm experiencing the exact same issue.

I try to stream to my Amazon Fire TV (2nd gen). First i thought its a wireless issue but even wired it is the same thing.

**Comment by TehRainbowGuy** [comment]
+1 Same issue with 53 games in GFE

**Comment by ecranegro** [comment]
I have the same exact problem. In the last days I ve been trying to find why this connection loss was happening. Fortunately I read this topic and now I understand the bug

**Comment by ManiacDC** [comment]
This might be the issue I'm having, I'm trying moonlight for the first time and "Nvidia Streamer Network Service" is exiting. This does NOT happen when I use my Nvidia Shield Portable, it gets the games fine.

GFE: 2.9.1.22
OS: Windows 7 Pro
Driver: 361.43

**Comment by OOPMan** [comment]
I was having this issue and switching back to GFE 2.5 fixed it. Not sure if it's the same issue though...

**Comment by OOPMan** [comment]
@cgutman I just did some testing and can conform that this does seem to be an issue tied to GFE >= 2.8 in conjunction with having more than a certain number of games in the library.

I tested with GFE 2.5, 2.8 and 2.9 in conjunction with two Android devices, my Note 10.1 (2014) and my XTreamer Prodigy 4K.

Under GFE 2.8 and 2.9 if I refresh the game list in GFE then attempt to connect with either Android device error "Connection to PC lost" occurs after Moonlight spends roughly a minute or so trying to sync the list of games from GFE.

This issue does not occur when running GFE 2.5.

The OP for this issue, @n1ckn4m3 theorized that the issue was related to the amount of RAM in his Android device but I'm not sure this is the cause of the issue (Unless the amount data sent from GFE to Moonlight during the sync process increased massively). Maybe there is some kind of infinite loop issue or something else due to some change in the data structures between GFE 2.5 and 2.8?

**Comment by ManiacDC** [comment]
BTW, Moonlight PC also won't get the game list for me... might be the same issue.

**Comment by ManiacDC** [comment]
Here is my nvstreamsvc folder:
https://drive.google.com/file/d/0B4sy4xxp8QsmMU5IQ3NPWVQxT00/view?usp=sharing

**Comment by OOPMan** [comment]
@ManiacDC I imagine it is the same issue. This problem has now been posted in about 4 separate issues with various titles...

**Comment by cgutman** [comment]
This issue seems to be that when the app list response size gets too large, GFE throws a 500 internal server error back. GFE 2.8 added SOPS (resolution and FPS info) to each app, increasing the size of the response per app significantly. I was able to reproduce the issue with SHIELD Hub when using PIN based pairing on my Portable.

The bug isn't in Moonlight; it's in GFE's server. There's no workaround possible besides reducing the number of games in the list, but I've filed a bug with NVIDIA for the PIN-based repro with SHIELD Hub. For some reason, it doesn't happen when using account-based pairing. 

@ManiacDC Can you confirm that if you remove your account from SHIELD Hub and pair via PIN (located in the settings of SHIELD Hub) that you also can't load the app list?

**Comment by OOPMan** [comment]
@cgutman Good to know we have some clarity on this. Sounds like the GFE server is up to shit...

**Comment by OOPMan** [comment]
@cgutman Is it possible to use account-based sharing with Moonlight?

**Comment by ManiacDC** [comment]
@cgutman Correct I can't load the app list when using pin based sharing on my shield portable, though the service doesn't seem to be crashing. Should I also report something to nvidia?

**Comment by OOPMan** [comment]
@cgutman Any idea whether Nvidia have fixed this in GFE 2.10 or 2.11?

**Comment by djrockgt** [comment]
I had to roll back to GFE 2.10 to get anything to Stream on any of my devices (Android, iOS, and Raspberry Pi).

**Comment by OOPMan** [comment]
@cgutman I just tested with GFE 2.10 and it *seems* like this issue has been fixed. My GFE currently lists 51 games detected and I was able to connect with the latest version of Moonlight. Moonlight display 65 games in the list of stream-able games. I'm not sure what the disconnect is there but comparing the two game lists a bunch of indie games that GFE doesn't bother to optimise but seems happy to stream are display.

@ManiacDC @DStBone @ecranegro @TehRainbowGuy @n1ckn4m3 Can you guys confirm the issue is fixed with GFE 2.10 and the most recent Moonlight?

**Comment by TehRainbowGuy** [comment]
I can confirm it now works with GFE 2.10.2.40 and Moonlight 4.5.3.

**Comment by OOPMan** [comment]
Nice! Good to know that Nvidia actually fix their bugs ;-)

**Comment by ManiacDC** [comment]
Sorry, I since reformatted my PC and I don't have so many games installed now ...

I did verify that I can see the applist on Moonlight PC now though, but I only have 25 games installed.

**Comment by voltagex** [comment]
I think this can be closed - I had this problem and don't have it any more. Tested from OS X client and Android client. I'll confirm the NVidia versions after (if) the system comes back up after updates.

**Comment by bynar010** [comment]
So this is what's being causing this, being banging my head off a wall wondering why everytime I opened my games list they would disappear.... Had to restart the nvidia streaming services to get it working. Counted my games list... 47 exactly listed, uninstalled and reinstalled GFE deleted all the game locations so it can't find any games and now works fine with just steam listed in there, can launch everything from there anyway.

**Comment by OOPMan** [comment]
@bynar010 The issue has been resolved. Update your Moonlight and GFE to the latest versions to correct the issue.

**Comment by bynar010** [comment]
Nope. Using the latest version of moonlight (beta) and running latest version of GFE (was happening on older versions too). Done clean installs of both moonlight and GFE and issue still persists. Happens on 2 different devices (nexus 6p / nexus player). Neither is rooted, using standard latest marshmallow build.

**Comment by OOPMan** [comment]
@bynar010 Hmmmm, that's odd. The issue was, in fact, a problem in GFE rather than Moonlight and was fixed in the 2.10.x release of GFE. What version of GFE are you running?

**Comment by bynar010** [comment]
2.11.2.55 , was happening on earlier versions too. Moonlight is at 4.5.6.

**Comment by OOPMan** [comment]
@bynar010 That's pretty weird. How many games do you have detected by GFE?

**Comment by bynar010** [comment]
Was 47 when I counted before I reinstalled GFE and cleared them all out. I can add them all back in and try see if it does it again, are there any logs I can capture that would assist in diagnosis either client or server side?

**Comment by OOPMan** [comment]
@bynar010 You would need to ask @cgutman about that.

**Comment by bynar010** [comment]
Ok, forget what I said above, its doing it again even when I remove all my games from GFE. Have to restart the streamer service on my PC (sometimes 2 or 3 times) before I can view my games list. I've dd cleaned my driver install and installed everything from scratch again and still doing it. Might open a new issue.....
