### ISSUE TITLE
error 532 GFE cannot pair client when server is locked

### ISSUE THREAD

**Issue by muffinmannameistaken** [moonlight-stream/moonlight-android#287]
I'm getting this error with the latest Geforce Version 3.0.7.34

**Comment by cgutman** [comment]
This is a GeForce Experience 3.0.7.34 bug. A reinstall of GeForce Experience should fix it.

**Comment by jgonyea** [comment]
I've uninstalled and reinstalled Geforce Version 3.0.7.34, but I'm still seeing this error on my laptop and Android device.

**Comment by jgonyea** [comment]
On my android, I see the pin code display for a moment, but then that window disappears and I see the error @muffinmannameistaken has described.

**Comment by cgutman** [comment]
This is a bug in the detection of auto-login in GFE 3.0.7. You can also workaround it by using Win+L to lock your PC then unlock it with your password.

**Comment by jgonyea** [comment]
@cgutman, your process worked for me.  I originally setup auto-login so I wouldn't have to type in a password if the machine rebooted.  I see now that a triple-finger tap on mobile will bring up the keyboard.

**Comment by cgutman** [comment]
NVIDIA released GFE 3.1.0.52 today that fixes the auto login bug.
