### ISSUE TITLE
Works on mobile / But constant "Conection terminated" with android TV. 

### ISSUE THREAD

**Issue by wolfeng-db** [moonlight-stream/moonlight-android#532]
NvStream log 
https://1drv.ms/u/s!AnGBLA6LcB3TiMAyPSo4HPwxtSlPhQ

Like the title says, I can launch both games and steam big picture on my mobile phone without issues, I can't comment on actual playing because my Wifi is unreliable. 

But when I install the application on my Android TV (running android 6.0), launching any of the Nvidia recognized games leads to a "connection terminated" a second after they launched. On the other hand trying to open steam big picture leads to an error about "Control stream establishment"

Sorry I don't remember the exact message, I've been going from my room to the living room for a while now and its tiring, with that said, is there any way I can disable the PIN code? At least while testing, because every time there's an error I have to type a new code.

**Comment by playerb0y** [comment]
Hello. Would like to bump this, have been having similar issue.

I have an Amlogic s912 box with custom Android TV 7.1.2 ROM, on a 5GHz WiFi with latest Moonlight (non root). Pairing works okay, can start game on app but after RTSP handshake, app crashes out to pairing screen with an error message 'PC not paired'. Then would have to restart the pairing process all over again, but streaming never works.

Steam Big Picture also gives out 'Control stream establishment' error message before crashing and resetting the paired connection.

I have another Amlogic s812 box running stock Android 5.1 and Moonlight (rooted) app, and streaming works fine on the same 5GHz network, so I deduce the problem lies either with the S912 chip, or Android TV, or the Android 7.1.2. Any idea?

**Comment by cgutman** [comment]
Heh, actually this is the result of a half-paired state caused by an inadvertent timeout occurring during the pairing process. If you typed the PIN within 10 seconds, it would work fine but if you took longer, it would get into this half-paired state where NvStreamer would sometimes fail.

Fixed by https://github.com/moonlight-stream/moonlight-common/commit/1480b1e7b848f3e4172c6b749bb3d9652217a81c

I will release v5.6.7 shortly with this change. Thanks for the reports.

**Comment by cgutman** [comment]
Fix released in v5.6.7

**Comment by CarlB86** [comment]
The control stream establishment error still occurs for me on 5.6.7 on a nexus 6 with Oreo 8.1.

**Comment by cgutman** [comment]
@CarlB86 do you get the same "PC not paired" message after the stream ends? Did you pair while on v5.6.7?

**Comment by CarlB86** [comment]
It pauses on "starting control stream establishment", then the error is "Connection Error Failed to start control stream establishment." 

I have not re-paired the phone, but will try uninstalling, re-installing, then re-pairing.

**Comment by cgutman** [comment]
@CarlB86 ah, probably Android Auto-Backup restoring your pairing keys back to the app after you reinstall.

But it doesn't sound like this issue, since you would become unpaired after the connection error. This issue is specifically to do with the half-paired state that results from a pairing timeout.

Since it pauses for a moment on "control stream establishment" it sounds like your firewall is blocking UDP 47999. I'd check on that if you're streaming locally, or if you're streaming remotely, make sure it's properly forwarded. If that doesn't work, open a new bug here.

**Comment by CarlB86** [comment]
Thanks @cgutman. My port forwarding on router hadn't changed, but apparently my windows firewall had. Everything had been working perfectly the week prior. I went and added the exceptions again using cmd line and now it is perfect again.
